name: enreda_empresas
description: Te ayudamos a construir tu futuro.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  provider: ^6.0.5
  google_fonts: ^5.1.0
  go_router: ^0.9.3
  layout: ^1.0.5
  email_validator: ^2.1.17
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.5.0
  flutter_staggered_grid_view: ^0.6.2
  image_picker: 1.0.0
  url_launcher: ^6.1.11
  country_code_picker: ^3.0.0
  datetime_picker_formfield_new: ^2.1.0
  sidebarx: ^0.16.0
  fluttertoast: ^8.2.2
  share_plus: ^7.0.2
  chips_choice: ^3.0.0
  pdf: ^3.10.7
  open_file: ^3.3.2
  printing: ^5.11.1
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_enreda.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/ic_enreda.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  macos:
    generate: true
    image_path: "assets/ic_enreda.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/a_dot_burr.jpeg
  #   - assets/a_dot_ham.jpeg

  assets:
    - assets/form-empresa-turquesa.png
    - assets/enreda-logo.png
    - assets/ic_enreda_bn.png
    - assets/ic_enreda.png
    - assets/enreda-mdpi.png
    - assets/icon-chat.png
    - assets/arrow_down.png
    - assets/arrow_up.png
    - assets/icon-resources-blue.png
    - assets/icon-resources-gray.png
    - assets/icon-cv.png
    - assets/icon-profile-blue.png
    - assets/icon-competencies-blue.png
    - assets/icon-fav-blue.png
    - assets/favorites-illustration.png
    - assets/enreda-logo-alone.png
    - assets/enreda-logo-text.png
    - assets/icon-download.png
    - assets/icon-logout.png
    - assets/logo-enreda-blanco.png
    - assets/icon-competencias.png
    - assets/placeholder-image.png
    - assets/play_store_900x503.png
    - assets/app_store_900x503.png
    - assets/user_default.jpg
    - assets/chica-lateral-formulario.png
    - assets/photo-button.jpg
    - assets/icon-crear-recurso.png
    - assets/icon-descargar.png
    - assets/icon-editar.png
    - assets/icon-eliminar.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
